# Generated by Django 6.0.6 on 2026-06-29 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_blogpost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
